### ISSUE TITLE
Add some ways to change the character

### ISSUE THREAD

**Issue by shunjizhan** [UCSB-CS56-Projects/cs56-games-pokemon-map#19]
Right now we can only control one character and one Pokemon, we can add some features that can change the character and Pokemon. For example by walking to some specific place on the map or simply by press some key on the keyboard. 
~250 points

**Comment by mbahia** [comment]
Approved M.B.

**Comment by MadRubicant** [comment]
F16 CLOSED; Way out of scope for project in its current form
