### ISSUE TITLE
fix the bug of the lake

### ISSUE THREAD

**Issue by shunjizhan** [UCSB-CS56-Projects/cs56-games-pokemon-map#21]
fix the bug that the lake edge will disappear when walk at the bottom of the lake (this bug should be closely related to the "Prof. Oak's hair visual bug #11")
~300 points

**Comment by mbahia** [comment]
Approved M.B.

**Comment by SElegans** [comment]
This bug is probably fixed, but we don't have an extensive enough program to test yet

**Comment by MadRubicant** [comment]
F16 CLOSED: The bug was destroyed during the summer rewrite
