### ISSUE TITLE
Add more buildings

### ISSUE THREAD

**Issue by shunjizhan** [UCSB-CS56-Projects/cs56-games-pokemon-map#23]
add more various buildings to the new map, which is pretty empty right now 
~200 points

**Comment by mbahia** [comment]
Approved M.B.

**Comment by MadRubicant** [comment]
F16 OK (200 pts)

**Comment by SElegans** [comment]
F17 OK (100 pts)

**Comment by SElegans** [comment]
F17 CLOSED (redundant issue)
