### ISSUE TITLE
Professor Oak turns into Pikachu when he walks into him

### ISSUE THREAD

**Issue by SElegans** [UCSB-CS56-Projects/cs56-games-pokemon-map#25]
Since Pikachu is always two spaces away from Professor Oak, if you turn around and move forward one space, Professor Oak's sprite will turn into Pikachu's sprite. 

Also If you walk on top of Pikachu, up or down, then off of him, a Pikachu clone will occur that doesn't move but tries. It follows the same animation as the original Pikachu sprite.

**Comment by xiaoheh** [comment]
Estimate: 150 pts

**Comment by SElegans** [comment]
This is probably fixed, but we are currently unsure on its status.

**Comment by MadRubicant** [comment]
F16 CLOSED: Cannot reproduce
