### ISSUE TITLE
Fix package structure

### ISSUE THREAD

**Issue by bkiefer13** [UCSB-CS56-Projects/cs56-games-pokemon-map#4]
The code currently uses the old Mantis-style packages names (e.g. edu.ucsb.cs56.S12.sbaldwin.pokemon) and accompanying directory structure. The directory structure should be modified to reflect the new style: src/edu/ucsb/cs56/projects/games/pokemon, corresponding to a package name of edu.ucsb.cs56.projects.games.pokemon

~50 points

**Comment by MadRubicant** [comment]
F16 OK (50 pts)

**Comment by MadRubicant** [comment]
Resolved
