### ISSUE TITLE
Missing Unit Tests

### ISSUE THREAD

**Issue by MadRubicant** [UCSB-CS56-Projects/cs56-games-pokemon-map#42]
There are no unit tests in the original repo

**Comment by MadRubicant** [comment]
There are currently some unit tests for the code, but more can be added

**Comment by MadRubicant** [comment]
Add more JUnit tests to objects without side-effects (things unrelated to rendering)

100 points

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by SElegans** [comment]
F17 OK (100 pts)

**Comment by SElegans** [comment]
F17 CLOSED
