### ISSUE TITLE
Memory leak in code

### ISSUE THREAD

**Issue by SElegans** [UCSB-CS56-Projects/cs56-games-pokemon-map#50]
There is a memory leak somewhere in the code. We suggest using a profiler to see what objects are allocated and which aren't being deallocated.

**Comment by xiaoheh** [comment]
Estimate: 150 pts

M16 OK

**Comment by MadRubicant** [comment]
F16 OK (150 pts)

**Comment by SElegans** [comment]
Not reproducable (Cited to be fixed)
F17 CLOSED
