### ISSUE TITLE
Implement the TileData ID system

### ISSUE THREAD

**Issue by jtbowman421** [UCSB-CS56-Projects/cs56-games-pokemon-map#56]
TileComponent currently is set up for an ID system for communication with TileData, which is not currently utilized. This could be utilized to enable referring to background tiles by ID only, making map design and creation simpler. 

Estimate: ~(100)

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by MadRubicant** [comment]
Resolved
