### ISSUE TITLE
Fix collision

### ISSUE THREAD

**Issue by DevonPorcher** [UCSB-CS56-Projects/cs56-games-pokemon-map#61]
There are instances where the collision component isn't functioning properly. It is currently in the movement system. Perhaps modify the movement system or move collision to a different spot.

**Comment by MadRubicant** [comment]
F16 OK (100 pts)

**Comment by SElegans** [comment]
F17 OK (100 pts)

**Comment by SElegans** [comment]
F17 CLOSED
