### ISSUE TITLE
Fix text to map generator

### ISSUE THREAD

**Issue by lyricluo** [ucsb-cs56-projects/cs56-games-pokemon-map#79]
Text to map generation is currently entirely broken. Previous groups hard-coded things in to fake it, but it doesn't work. Rewrite this so that a text file can be translated into an actual map. Make sure that objects generated can be collided with if they are obstacles and these obstacles cover the entire image. Feel free to change the format of the text file to make it cleaner. 

Estimated: 500 points

**Comment by Sierrasch** [comment]
W18 OK (500 pts)

**Comment by Sierrasch** [comment]
W18 Done
