### ISSUE TITLE
Add talking ability to Pikachu or other Sprites that get added

### ISSUE THREAD

**Issue by alecharrell** [UCSB-CS56-Projects/cs56-games-pokemon-map#9]
Allow the player to interact with Pikachu or add other Sprites on the map that can be interacted with

~150 points

**Comment by shunjizhan** [comment]
we can press "h" to interact with big robot in the forest, the big pokemon behind the blue house (in a particular stage of the game) and the pokemon ball in the desert (in a particular stage of the game)

**Comment by MadRubicant** [comment]
Issue was resolved previously but never closed
